const nodemailer = require('nodemailer');

/**
 * Creates and returns a configured Nodemailer transporter.
 * Supports Gmail by default. Adjust host/port for other providers.
 */
const createTransporter = () => {
  const user = process.env.EMAIL_USER;
  const pass = process.env.EMAIL_PASS;

  if (!user || !pass) {
    throw new Error('EMAIL_USER and EMAIL_PASS must be set in environment variables.');
  }

  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user,
      pass,
    },
  });
};

/**
 * Sends the AI-generated executive summary to the recipient email.
 * @param {string} recipientEmail - The recipient's email address
 * @param {string} summary - The AI-generated summary text
 * @param {string} fileName - Original uploaded file name (for reference)
 */
const sendSummary = async (recipientEmail, summary, fileName) => {
  const transporter = createTransporter();

  const htmlBody = buildEmailHTML(summary, fileName);
  const textBody = buildEmailText(summary, fileName);

  const mailOptions = {
    from: `"Sales Insight Automator" <${process.env.EMAIL_USER}>`,
    to: recipientEmail,
    subject: `📊 Sales Executive Summary — ${fileName}`,
    text: textBody,
    html: htmlBody,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log(`[Email] Message sent: ${info.messageId}`);
    return info;
  } catch (error) {
    throw new Error(`Email delivery failed: ${error.message}`);
  }
};

/**
 * Builds the plain-text version of the email.
 */
const buildEmailText = (summary, fileName) => {
  return `Sales Executive Summary
Generated from: ${fileName}
Generated on: ${new Date().toLocaleString()}

${summary}

---
This report was automatically generated by Sales Insight Automator.
Powered by Rabbitt AI.`;
};

/**
 * Builds the HTML version of the email for rich rendering.
 */
const buildEmailHTML = (summary, fileName) => {
  // Convert plain text summary to HTML paragraphs (preserving bullet points)
  const formattedSummary = summary
    .split('\n')
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return '';
      if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
        return `<li style="margin-bottom:6px;">${trimmed.slice(2)}</li>`;
      }
      return `<p style="margin:8px 0;">${trimmed}</p>`;
    })
    .join('\n');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body style="margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;background:#f4f6f9;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
          
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%);padding:36px 40px;text-align:center;">
              <h1 style="color:#e2b96f;margin:0;font-size:22px;font-weight:700;letter-spacing:1px;">
                📊 Sales Executive Summary
              </h1>
              <p style="color:#a0aec0;margin:8px 0 0;font-size:13px;">
                Generated from: <strong style="color:#e2b96f;">${fileName}</strong>
              </p>
              <p style="color:#718096;margin:4px 0 0;font-size:12px;">
                ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:36px 40px;color:#2d3748;font-size:15px;line-height:1.7;">
              <div style="background:#f7f9fc;border-left:4px solid #e2b96f;padding:20px 24px;border-radius:0 8px 8px 0;margin-bottom:24px;">
                <p style="margin:0;color:#4a5568;font-size:13px;text-transform:uppercase;letter-spacing:1px;font-weight:600;">
                  AI-Generated Analysis
                </p>
              </div>
              <div style="color:#2d3748;">
                ${formattedSummary}
              </div>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#f7f9fc;padding:20px 40px;text-align:center;border-top:1px solid #e2e8f0;">
              <p style="color:#a0aec0;margin:0;font-size:12px;">
                Automatically generated by <strong style="color:#4a5568;">Sales Insight Automator</strong>
                &nbsp;•&nbsp; Powered by <strong style="color:#4a5568;">Rabbitt AI</strong>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
};

module.exports = { sendSummary };
